module.exports = {
    addLabelToCardSuccessfully: "Thêm nhãn vào thẻ thành công.",
    addMemmberToBoardSuccessfully: "Thêm thành viên vào bảng thành công.",
    boardDescriptionExceedsAllowedLength:
        "Mô tả bảng không được vượt quá 65535 ký tự.",
    boardDoesNotExist: "Bảng không tồn tại.",
    boardTitleCannotBeEmpty: "Tên bảng không được để trống.",
    boardTitleExceedsAllowedLength: "Tên bảng không được vượt quá 255 ký tự.",
    changePasswordSuccessfully: "Đổi mật khẩu thành công",
    closeBoardSuccessfully: "Đóng bảng thành công.",
    confirmPasswordDoesNotMatch: "Mật khẩu xác nhận không trùng khớp.",
    createBoardSuccessfully: "Tạo bảng thành công.",
    dataConflict: "Xung đột dữ liệu.",
    emailAlreadyExists: "Email đã tồn tại.",
    emailCannotBeEmpty: "Email không được để trống.",
    emailExceedsAllowedLength: "Email không được vượt quá 100 ký tự.",
    emailInvalidate: "Email không đúng định dạng.",
    forbidden: "Bạn không có quyền truy cập tài nguyên.",
    fullNameCannotBeEmpty: "Họ tên không được để trống.",
    fullNameExceedsAllowedLength: "Họ tên không được vượt quá 100 ký tự.",
    internalServerError: "Lỗi máy chủ.",
    invalidInput: "Đầu vào không hợp lệ.",
    labelAlreadyAddedInCard: "Nhãn đã được thêm vào thẻ.",
    logOutSuccessfully: "Đăng xuất thành công.",
    notFound: "Không tìm thấy tài nguyên.",
    passwordCannotBeEmpty: "Mật khẩu không được để trống.",
    passwordExceedsAllowedLength: "Mật khẩu không được vượt quá 255 ký tự",
    passwordIsTooShort: "Mật khẩu không ít hơn 8 ký tự.",
    removeMemberFromBoardSuccessfully: "Xoá thành viên khỏi bảng thành công.",
    signUpSuccess: "Đăng ký thành công.",
    unauthorized: "Xác thực không thành công.",
    updateMemmberRoleSuccessfully: "Cập nhật vai trò người dùng thành công.",
    updateSuccessfully: "Cập nhật thành công.",
    userAlreadyMemberOfBoard: "Người dùng vốn đã được thêm vào bảng.",
    userDeleted: "Đã xoá người dùng.",
    userDoesNotExist: "Người dùng không tồn tại.",
    userHasNoBoards: "Người dùng không có bảng nào.",
    userIsNotAMember: "Người dùng không phải thành viên của bảng.",
    userNameAlreadyExists: "Tên người dùng đã tồn tại.",
    userNameCannotBeEmpty: "Tên người dùng không được để trống.",
    userNameDoesNotContainSpecialCharacters:
        "Tên người dùng không chứa các ký tự đặc biệt.",
    userNameExceedsAllowedLength:
        "Tên người dùng không được vượt quá 50 ký tự.",
    wrongUsernameOrPassword: "Tên đăng nhập hoặc mật khẩu không đúng.",
    wrongPassword: "Mật khẩu không đúng.",
};
